### ISSUE TITLE
Menu navigation screens don't call ProMotion view lifecycle methods

### ISSUE THREAD

**Issue by markrickert** [clearsightstudio/ProMotion-menu#47]
A left or right menu that is a PM::Screen doesn't get sent the normal PM lifecycle methods like `will_appear`, `did_appear`, etc. However you can implement their objective-c counterparts and they'll be called.

```ruby
class NavigationScreen < ProMotion::TableScreen
  def viewWillAppear(animated)
    # This will be called
  end

  def will_appear
    # This will not be called
  end
```

I have tests that fail for this scenario but i can't push them up at the moment because the public library I'm at blocks port 22 :cry:

**Comment by jamonholmgren** [comment]
This is strange. `viewWillAppear(animated)` should delegate through `view_will_appear(animated)` and subsequently `will_appear`.

**Comment by markrickert** [comment]
@jamonholmgren I just pushed up the failing tests so you can take a look.

**Comment by jamonholmgren** [comment]
OK thanks @markrickert !

**Comment by jamonholmgren** [comment]
@ryanlntn , would you want to take a look?

**Comment by ryanlntn** [comment]
On it @jamonholmgren !

**Comment by ryanlntn** [comment]
@markrickert @jamonholmgren defining `view_will_appear(animated)` in the screen causes specs to pass. I'm still not sure why that isn't in turn calling `will_appear`.

**Comment by jamonholmgren** [comment]
@ryanlntn Do you mean defining it [like this](https://github.com/clearsightstudio/ProMotion/blob/master/lib/ProMotion/screen/screen_module.rb#L69-L74)? Perhaps the side screens aren't including `PM::ScreenModule` properly?

**Comment by ryanlntn** [comment]
@jamonholmgren Yep. The side screens are just `PM::TableScreen`s. We're not doing anything different there.

**Comment by ryanlntn** [comment]
@markrickert I took a look at this again today and I think the issue may actually be with the tests and not the lifecycle methods. The [simple app](https://github.com/ryanlntn/pm-menu-issue-47) that I spun up to try to recreate this does call the lifecycle methods: [Video](http://clrsight.co/rl/ih7wstuszv_0_edited.mp4)

**Comment by ryanlntn** [comment]
@markrickert Closing this issue for now. Feel free to reopen if I'm missing something.
